dataset_name: 'brain'
dataset_path: '$CUTS_ROOT/data/brain_arman/'
supervised_network: 'nnunet'
model_save_path: '$CUTS_ROOT/checkpoints/supervised_brain_nnunet_seed2023.pty'
output_save_path: '$CUTS_ROOT/results/brain_seed2023/'
log_folder: '$CUTS_ROOT/logs'
learning_rate: 1e-3
weight_decay: 1e-4
max_epochs: 200
patience: 10
batch_size: 16
num_workers: 8
random_seed: 2023
train_val_test_ratio: '7:1:2'
pretrained: False